import Head from 'next/head';

import { menuItems } from '@/config/mocks';
import Navbar from '@/core/components/Navbar'
import Footer from '@/core/components/Footer';

import styles from "@/core/components/PageLayout/PageLayout.module.css";

interface IPageLayout {
    title: string;
    children: React.ReactNode;
}

const PageLayout = ({ title, children }: IPageLayout) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar appTitle={title} navItems={menuItems} />

            <main className={styles.main}>
                {children}
            </main>

            <Footer />
        </>
    );
}

export default PageLayout;